/**
 * Discord OAuth2 + permission resolution.
 *
 * OAuth uses the `identify` + `guilds` scopes only. After the code
 * exchange we have the user's Discord ID and the list of guilds they're
 * in. To check whether they can edit a given guild's config, we fetch
 * the member object via the bot token (using `guilds.members.read` in
 * OAuth would require per-guild authorization) and apply the same logic
 * the bot uses in `GuildConfig.hasPermission`.
 */
import { randomBytes } from "node:crypto";
import { env } from "@lib/env";
import { fetchMember, type DiscordMember } from "@lib/discord";
import { Permission, type RawGuildConfig } from "@/schema";

const DISCORD_OAUTH = "https://discord.com/oauth2/authorize";
const DISCORD_TOKEN = "https://discord.com/api/oauth2/token";
const DISCORD_USER = "https://discord.com/api/users/@me";
const DISCORD_USER_GUILDS = "https://discord.com/api/users/@me/guilds";
const SCOPES = "identify guilds";

export interface DiscordUser {
	id: string;
	username: string;
	avatar: string | null;
}

export interface UserGuild {
	id: string;
	name: string;
	icon: string | null;
}

/**
 * Build the OAuth authorize URL. `state` should be generated by the caller
 * via {@link generateState} and round-tripped through a short-lived signed
 * cookie for CSRF protection on the callback.
 */
export function buildAuthorizeUrl(state: string): string {
	const params = new URLSearchParams({
		client_id: env.discord.clientId,
		redirect_uri: env.discord.redirectUri,
		response_type: "code",
		scope: SCOPES,
		state,
		prompt: "none"
	});
	return `${DISCORD_OAUTH}?${params}`;
}

export function generateState(): string {
	return randomBytes(16).toString("base64url");
}

interface TokenResponse {
	access_token: string;
	token_type: string;
	expires_in: number;
	refresh_token?: string;
	scope: string;
}

export async function exchangeCode(code: string): Promise<TokenResponse> {
	const body = new URLSearchParams({
		client_id: env.discord.clientId,
		client_secret: env.discord.clientSecret,
		grant_type: "authorization_code",
		code,
		redirect_uri: env.discord.redirectUri
	});
	const res = await fetch(DISCORD_TOKEN, {
		method: "POST",
		headers: { "content-type": "application/x-www-form-urlencoded" },
		body
	});
	if (!res.ok) {
		const text = await res.text().catch(() => "");
		throw new Error(`OAuth code exchange failed (${res.status}): ${text}`);
	}
	return await res.json() as TokenResponse;
}

export async function fetchOAuthUser(accessToken: string): Promise<DiscordUser> {
	const res = await fetch(DISCORD_USER, { headers: { Authorization: `Bearer ${accessToken}` } });
	if (!res.ok) throw new Error(`Failed to fetch Discord user (${res.status})`);
	const user = await res.json() as DiscordUser;
	return { id: user.id, username: user.username, avatar: user.avatar };
}

export async function fetchOAuthGuilds(accessToken: string): Promise<UserGuild[]> {
	const res = await fetch(DISCORD_USER_GUILDS, { headers: { Authorization: `Bearer ${accessToken}` } });
	if (!res.ok) throw new Error(`Failed to fetch user guilds (${res.status})`);
	const arr = await res.json() as UserGuild[];
	return arr.map(g => ({ id: g.id, name: g.name, icon: g.icon }));
}

/**
 * Decide whether `userId` can edit `guildId`'s config. Mirrors
 * `GuildConfig.hasPermission` from the bot's
 * `src/managers/config/GuildConfig.ts`. Returns the rationale ("bootstrap"
 * vs "permission") for the audit log.
 */
export async function authorizeGuildEdit(
	userId: string,
	guildId: string,
	config: RawGuildConfig | null
): Promise<{ allowed: true; via: "bootstrap" | "permission" } | { allowed: false; reason: string }> {
	if (env.bootstrapUserIds.has(userId)) {
		return { allowed: true, via: "bootstrap" };
	}

	if (!config?.permissions || config.permissions.length === 0) {
		return { allowed: false, reason: "No permissions configured for this guild yet — bootstrap an admin first" };
	}

	let member: DiscordMember | null;
	try {
		member = await fetchMember(guildId, userId);
	} catch (err) {
		return { allowed: false, reason: `Failed to verify membership: ${err instanceof Error ? err.message : String(err)}` };
	}

	if (!member) {
		return { allowed: false, reason: "Not a member of this guild" };
	}

	const memberRoleIds = new Set(member.roles);
	const granted = config.permissions.some(p =>
		p.allow.includes(Permission.ManageGuildConfig) &&
		p.roles.some(roleId => memberRoleIds.has(roleId))
	);

	return granted
		? { allowed: true, via: "permission" }
		: { allowed: false, reason: "Missing manage_guild_config permission" };
}
